import { EquipmentFeatureType } from '../types'

export const descriptionMapping: Record<EquipmentFeatureType, string> = {
  air_conditioner: 'Klimaanlage',
  baby_bed: 'Baby Bett',
  balcony: 'Balkon',
  barrier_free: 'Barrierefrei',
  bathtub: 'Badewanne',
  bed_linen: 'Bettwäsche',
  coffee_machine: 'Kaffeemaschine',
  cooker: 'Herd',
  dishes: 'Geschirr',
  fire_extinguisher: 'Feuerlöscher',
  freezer: 'Gefrierschrank',
  hairdryer: 'Föhn',
  high_chair: 'Hochstuhl',
  microwave: 'Mikrowelle',
  oven: 'Backofen',
  pots_pans: 'Töpfe / Pfanne',
  refrigerator: 'Kühlschrank',
  shower: 'Dusche',
  smoke_detector: 'Rauchmelder',
  terrace: 'Terrasse',
  towels: 'Handtücher',
  vacuum: 'Staubsauger',
  washing_rack: 'Wäscheständer',
  parking: 'Parkmöglichkeit',
  tv: 'Fernsehr',
  wlan: 'WLAN',
  washing_machine: 'Waschmaschine',
  pool: 'Pool',
}
